general {
    ignore_dbus_inhibit = false
}



# 5 min — lock the session
listener {
    timeout = 300
    on-timeout = hyprlock
}

# 15 min — suspend
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
